In [49]:
# Import modules
import pandas as pd

#from utils import *

from warrant_alert_generator import *

from warrant_aevaleva import *

In [5]:
# read in the filtered selection and display all warrants that satisfy the above filter
df = pd.DataFrame.from_csv('warrants_filtered_selection.csv', index_col=None, )

###==>  df

In [6]:
# calculate strenght of the alert signal - looking for at least 0.80

# DESCRIBE what it does
df['alert'] = df.apply(lambda row: gen_alert(row['leverage'], row['price-time-gain'], row['warrant']), axis=1)

# DESCRIBE what it does
df['avg_lvge'] = df.apply(lambda row: gen_avealeva(row['stock'], row['warrant'], row['exercise-price']), axis=1)

df

,company,symbol,stock,exercise-price,warrant,leverage,expiry-date,price-time-gain,alert,avg_lvge
0,Acasta Enterprises Inc,AEF.WT,8.750,11.50,1.200,7.3,03/01/2022,0.02,0.88,4.18
1,Kew Media Group Inc,KEW.WT,9.850,11.50,1.670,5.9,13/06/2023,0.01,0.89,3.01
2,Manitok Energy Inc,MEI.WT,0.115,0.18,0.025,4.6,15/11/2021,0.03,0.98,2.36
3,Osisko Gold Royalties Ltd,OR.WT,14.260,36.50,2.400,5.9,18/02/2022,0.09,0.79,3.09
4,Titan Medical Inc,TMD.WT.G,0.353,1.00,0.030,11.8,12/02/2021,0.14,0.93,6.32
5,Titan Medical Inc,TMD.WT.H,0.353,1.20,0.035,10.1,31/03/2021,0.18,0.91,5.28
6,Titan Medical Inc,TMD.WT.I,0.353,0.75,0.060,5.9,20/09/2021,0.07,0.95,3.11
7,Trilogy Intl Partners Inc,TRL.WT,9.500,11.50,0.500,19.0,07/02/2022,0.01,0.89,12.78

In [45]:
notnull_color = 'yellow'
df.style.applymap(lambda x: 'background-color: %s' % notnull_color if pd.notnull(x) else '')

#df.style.apply(lambda x: 'background-color: %s' % notnull_color if df.notnull(x) else '', subset=['alert'])

In [52]:
html = df.style.background_gradient(cmap='viridis', low=.8)
html

TypeError: ("unsupported operand type(s) for -: 'str' and 'str'", 'occurred at index alert')

In [50]:
def highlight_max(s):
    '''
    highlight the maximum in a Series yellow.
    '''
    is_max = s == s.max()
    return ['background-color: #de4188' if v else '' for v in is_max]

df

,company,symbol,stock,exercise-price,warrant,leverage,expiry-date,price-time-gain,alert,avg_lvge
0,Acasta Enterprises Inc,AEF.WT,8.750,11.50,1.200,7.3,03/01/2022,0.02,0.88,4.18
1,Kew Media Group Inc,KEW.WT,9.850,11.50,1.670,5.9,13/06/2023,0.01,0.89,3.01
2,Manitok Energy Inc,MEI.WT,0.115,0.18,0.025,4.6,15/11/2021,0.03,0.98,2.36
3,Osisko Gold Royalties Ltd,OR.WT,14.260,36.50,2.400,5.9,18/02/2022,0.09,0.79,3.09
4,Titan Medical Inc,TMD.WT.G,0.353,1.00,0.030,11.8,12/02/2021,0.14,0.93,6.32
5,Titan Medical Inc,TMD.WT.H,0.353,1.20,0.035,10.1,31/03/2021,0.18,0.91,5.28
6,Titan Medical Inc,TMD.WT.I,0.353,0.75,0.060,5.9,20/09/2021,0.07,0.95,3.11
7,Trilogy Intl Partners Inc,TRL.WT,9.500,11.50,0.500,19.0,07/02/2022,0.01,0.89,12.78

In [47]:
def color_negative_red(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    color = 'red' if val >= 0.8 else 'black'
    return 'color: %s' % color

df.style.applymap(color_negative_red, subset=['alert', 'avg_lvge'])
df

,company,symbol,stock,exercise-price,warrant,leverage,expiry-date,price-time-gain,alert,avg_lvge
0,Acasta Enterprises Inc,AEF.WT,8.750,11.50,1.200,7.3,03/01/2022,0.02,0.88,4.18
1,Kew Media Group Inc,KEW.WT,9.850,11.50,1.670,5.9,13/06/2023,0.01,0.89,3.01
2,Manitok Energy Inc,MEI.WT,0.115,0.18,0.025,4.6,15/11/2021,0.03,0.98,2.36
3,Osisko Gold Royalties Ltd,OR.WT,14.260,36.50,2.400,5.9,18/02/2022,0.09,0.79,3.09
4,Titan Medical Inc,TMD.WT.G,0.353,1.00,0.030,11.8,12/02/2021,0.14,0.93,6.32
5,Titan Medical Inc,TMD.WT.H,0.353,1.20,0.035,10.1,31/03/2021,0.18,0.91,5.28
6,Titan Medical Inc,TMD.WT.I,0.353,0.75,0.060,5.9,20/09/2021,0.07,0.95,3.11
7,Trilogy Intl Partners Inc,TRL.WT,9.500,11.50,0.500,19.0,07/02/2022,0.01,0.89,12.78